### ISSUE TITLE
can't add translations

### ISSUE THREAD

**Issue by giokaxo** [dimsav/laravel-translatable#255] opened 2016-08-04 18:48 UTC
Hello, i'm trying to add translations from json, but they aren't saving.

i send data like this:

`en: {summary: "random summary"}
ru:  {summary: "random summary"}`

it creates new record, but without translations. any ideas?

**Comment by johannesschobel** [comment] 2016-08-08 15:43
I stumbled upon the same problem. However, I was not sure, if it was my fault, because of lack of sleep ;)
However, I will try to enforce the bug by myself and post a full example here in order to validate.

**Comment by dimsav** [comment] 2016-08-08 15:56
Can you please share some code here? All the supported ways of adding translations can be found in the [tests](https://github.com/dimsav/laravel-translatable/tree/master/tests)

**Comment by johannesschobel** [comment] 2016-08-08 17:10
Hey @dimsav ,

I just tried to re-create the bug explained above in my current project I work on.
Consider the following situation:

I have a ```Faq``` model, like this:
```php
class Faq extends Model
{
    use Translatable;
    protected $fillable = ['name'];

    public $translatedAttributes  = ["title", "question", "answer"];
}
```

and the respective translation model ```FaqTranslation```, which looks like this:
```php 
class FaqTranslation extends Model
{
    protected $fillable = ['title', 'question', 'answer'];
}
```

If I try to create a new ```Faq``` entry using the following syntax (as you describe in your readme file), I get an empty result for ```$faq->translations()->get()```.

```php
$data = [
   "name" => "name",
   "en" => ["title" => "EN title", "question" => "EN question", "answer" => "EN answer"],
   "de" => ["title" => "DE title", "question" => "DE question", "answer" => "DE answer"],
];
$faq = Faq::create($data);
dd($faq->translations()->get()); // this outputs an empty collection
```

As far as I can see, the problem is within the ```save()``` method in the ```Translatable``` trait.
If the parent model (in this case, the ```Faq```) can be saved, it calls the ```saveTranslations()``` method. However, ```$this->translations``` is empty.

Hope this helps?!
Greetings and Cheers

**Comment by johannesschobel** [comment] 2016-08-08 17:12
Oh, by the way: I am using Laravel 5.1!

Another thing, I am curious about:
In your ```TranslatableTest``` you actually do the same thing:
```php
$data = [
   'id' => 1,
   'fr' => ['name' => 'frites'],
];
Food::create($data);
```
and it looks like this test passes?!

**Comment by dimsav** [comment] 2016-08-17 08:04
Hi Johannes,

sorry for the late reply (I'm in semi-vacation mode). Have you properly defined the locales in your configuration? 

```php
dd(app()->make('config')->get('translatable.locales'));
```

**Comment by johannesschobel** [comment] 2016-08-17 09:30
I need to check this later today.. Maybe at evening..

**Comment by johannesschobel** [comment] 2016-08-18 13:59
My config looks like this:
```php
array:2 [
  0 => "en"
  1 => "de"
]
```

In other words: I try to add languages, which are defined in the config file.

**Comment by dimsav** [comment] 2016-08-18 14:03
Sorry I can't think of anything else. If I was you, I would try to debug inside the `create()` method and see what's wrong.

**Comment by johannesschobel** [comment] 2016-08-18 14:05
I will look into it.. I will give feedback as soon as I stumble upon something fishy ;)

**Comment by PawelMysior** [comment] 2016-08-24 07:39
@johannesschobel Hey, I'm having the exact same problem. I'm have been debbuging this for the last two hours, no luck yet. Did you maybe find a solution?

**Comment by johannesschobel** [comment] 2016-08-24 07:49
Hey @PawelMysior, sorry, I haven't had the time yet.. However, I hope I am able to spend 2-3 hours on this problem at the weekend..

**Comment by PawelMysior** [comment] 2016-08-24 07:57
I'm using custom primary keys, maybe there's a problem there. Will let you know if I find something.

**Comment by johannesschobel** [comment] 2016-08-24 08:02
Should not be the problem. I am using the default primary key for the models (that is the field `id`), however, I am using a custom model (which is located in a specific `Translations` namespace.

**Comment by PawelMysior** [comment] 2016-08-24 08:40
Well, got it. At least for my case. What I did was put the names of fields from the translations table in the **main model** `fillable` property.

**Comment by johannesschobel** [comment] 2016-08-24 08:53
Do you need to add the fields to `$fillable` **AND** to `$translatedAttributes`?

**Comment by PawelMysior** [comment] 2016-08-24 09:02
If you update to version ^6.0 it shouldn't be a problem.

**Comment by johannesschobel** [comment] 2016-08-24 09:55
I'm still using `v 5.6.*`, I guess i will be switching to `v 6.0.*` for my laravel 5.1. project. I will post feedback regarding the issue. Maybe it is solved for the new version..

**Comment by johannesschobel** [comment] 2016-08-24 10:20
ok.. for `v 6.0.1` the following solution works for me:

in your `Faq` model, add the following lines:
```php
protected $fillable = ['name', 'is_active', 'title', 'question', 'answer'];
public $translatedAttributes  = ['title', 'question', 'answer'];
```

where `$fillable` holds all fields of the `Faq` model **AND** all fields of the `FaqTranslation` model.

This is kind of redundant, but it works ;)
Problem could be, that if you add a field in `FaqTranslation` model, you need to add it to `$translatedAttributes` and `$fillable` in `Faq` Model as well.. I see, that I will run into this error some day ;)

**Comment by dimsav** [comment] 2016-08-24 10:40
@johannesschobel the redudancy issue you mentioned was one of the main fixes in v6.

[Change log](https://github.com/dimsav/laravel-translatable/blob/master/changelog.md#v-60)

**Comment by johannesschobel** [comment] 2016-08-24 11:27
I see @dimsav , however I still need the 
```php
public translatedAttributes = [...];
```
part, inside the main model, right?

**Comment by johannesschobel** [comment] 2016-08-24 15:17
@giokaxo try with the new `v 6.0.*` - this worked for me!
Also - you need to add the `$translatedAttributes` array..

**Comment by dimsav** [comment] 2016-08-27 22:26
Can we close this?

**Comment by johannesschobel** [comment] 2016-08-27 22:27
For me it is solved..

Am 28.08.2016 12:26 vorm. schrieb "Dimitris Savvopoulos" <
notifications@github.com>:

**Comment by dimsav** [comment] 2016-08-27 22:34
Seems it worked for @giokaxo as well. Closing

**Closed by dimsav** 2016-08-27 22:34 UTC
