### ISSUE TITLE
Translate not working on save

### ISSUE THREAD

**Issue by madscientist667** [dimsav/laravel-translatable#237] opened 2016-04-18 20:29 UTC
I have a Model Category:

        use Illuminate\Database\Eloquent\Model;
        use Dimsav\Translatable\Translatable;
        class Category extends Model {
                use Translatable;
                public $translatedAttributes = ['name'];
         }

A CategoryTranslation:

        use Illuminate\Database\Eloquent\Model;
        class CategoryTranslation extends Model {
                 public $timestamps = false;
        }

And in Controller when I try to save this with a specific language I get an error. This is my controller:

        $language = App::getLocale();
        $user = Auth::user();
        $category = new Category();
        $category->translate('en')->name = Input::get('name');  //line 35
        $category->save()) 

And error:

> at HandleExceptions->handleError('2', 'Creating default object from empty value', 'C:\workspace\applications\wamp\www\lutz-paletten\app\Http\Controllers\CategoryController.php', '35', array('language' => 'en', 'user' => object(User), 'category' => object(Category))) in CategoryController.php line 35

PS: this is my migration:

        Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
           $table->integer('categoryId');
           $table->integer('user_id');
           $table->timestamps();
        });

        Schema::create('category_translations', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('category_id')->unsigned();
            $table->string('name');
            $table->string('locale')->index();

            $table->unique(['category_id','locale']);
            $table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
        });

What am I missing ? 
If I use this, it works:
         `$category->name = Input::get('name'); `

And it will be saved with what is set as AppLocale but how can I use it with 'translate()' ?

**Comment by dimsav** [comment] 2016-04-21 17:28
I think the issue is that `category->translate('en')` is not an object, can you check?

**Comment by dimsav** [comment] 2016-04-21 17:29
Also this is a bad practice. Always make sure that `$category->translate('en')` is an object before doing anything else with it.

**Comment by madscientist667** [comment] 2016-04-21 18:36
How can I make sure that is an object ? I am new to this syntax. Overall I do not think that is an object and that might be the issue. Only $category is the object. But I don't know how to fix it..

**Comment by dimsav** [comment] 2016-04-21 22:17
See more info [here](https://www.google.gr/#q=php+is+object)

Closing because the issue is not related to the package

**Closed by dimsav** 2016-04-21 22:17 UTC
