### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by ahmedalmulki** [dimsav/laravel-translatable#330] opened 2017-03-27 16:13 UTC
I have Tag table has relation with Post table , before I translate my Project I was using the following function in AppServiceProvider.php  "Tag::has('post')->pluck('name')" to get tag name , Now I want to get tag name according with the post language , so if I am in fr locale I will get the tag names related with this language and same in en .
Thanks in advance .

**Comment by Gummibeer** [comment] 2017-03-28 07:55
Why do you query all tags with posts but want the tags to be in the post language they are assigned to? And more important: is it not possible in your setup that a tag is assigned to multiple posts in different languages!?

I think that you have to loop over all tags to get a right result - if I get the question right.

one tag has one post
```php
$tags = Tag::has('post')->get(); // shouldn't it be posts - because of a belognsToMany() relation?
$translatedTags = [];
foreach($tags as $tag) {
  $locale = $tag->post->locale;
  $key = $locale.'-'.$tag->getKey();
  if(!array_key_exists($key, $translatedTags)) {
    $translatedTags[$key] = $tag->translate($locale)->name;
  }
}
```

one tag has multiple posts
```php
$tags = Tag::has('posts')->get();
$translatedTags = [];
foreach($tags as $tag) {
  foreach($tag->posts as $post) {
    $locale = $post->locale;
    $key = $locale.'-'.$tag->getKey();
    if(!array_key_exists($key, $translatedTags)) {
      $translatedTags[$key] = $tag->translate($locale)->name;
    }
  }
}
```

If you want to get all tags in the same language
```php
Tag::has('post')->withTranslation()->pluck('name'); // app locale for translation
Tag::has('post')->listsTranslations('name')->get()->toArray(); // app locale for translation
Tag::has('post')->withTranslation()->pluck('name:'.$locale); // $locale for translation
```

**Comment by ahmedalmulki** [comment] 2017-03-28 15:09
Thanks  @Gummibeer  for help Tag::has('post')->withTranslation()->pluck('name'); is working like I want now I can get all translated tag in my sidebar , but I face another problem when I click on the tag I get error ,

web.php 

`Route::get('/posts/tag/{tag}','TagController@index');`

TagController.php

`    public function index(Tag $tag){
        $posts = $tag->post;
        return view('posts.index', compact('posts'));
    }`

how can I solve this because it give me  Unknown column 'name' .

Thanks again .

**Comment by Gummibeer** [comment] 2017-03-28 18:21
Without the stacktrace it will be hard to tell you where the problem is. :/

**Comment by ahmedalmulki** [comment] 2017-03-28 20:54
The problem is when I make an argument from Tag table "Tag $tag" , I can't bring name column from TagTranslation , and when I change Tag to TagTranslation I can't call post function 
` public function post()
            {
                return $this->belongsToMany(Post::class);
            }` 
from Tag class to get the post , sorry @Gummibeer  for that , but I am new with laravel .
please let me know if you want any more clarification .

**Comment by Gummibeer** [comment] 2017-03-28 21:45
The `getRouteKeyName()` is new in L5.4!? And is similar to the normal `getKeyName()`!?

I think that this isn't solvable with default logic. My approach to solve it would be a slug column on the Tag model - this column is everytime english and slugged `str_slug()` as a hint.
With this you are url save and have a human readable url, not `/tag/1`.
Otherwise the only solution would be to define tge reverse relation on the TagTranslation model. But this isn't recommended - cause translated names are by no way unique identifiers. Using the slug and a `do-while` to add numbers to it if there is already a tag with this slug is the way to go I think.

**Comment by ahmedalmulki** [comment] 2017-03-29 16:16
Hi @Gummibeer  I solve my problem  , by change the href from "/posts/tag/{{$mytags->name}}" to "/posts/tag/{{$mytags->id}}" , I don't know what happen but its work :) , 
 Last question I was using firstOrCreate on my store function  
`$tagID = Tag::firstOrCreate(['name' => request('tag')]);` now after translation how can I use translateOrNew to create tag translation , or should I use something else .
Thanks again .

**Closed** 2017-05-25 14:03 UTC
