### ISSUE TITLE
Is there are reason why the saved/updated events are fired even when there are no changes?

### ISSUE THREAD

**Issue by wyred** [dimsav/laravel-translatable#333] opened 2017-04-03 03:04 UTC
I'm using laravel-translatable with laravel-auditing in a single model which causes auditing to create a log entry even though there are no changes.

https://github.com/owen-it/laravel-auditing/issues/221

**Comment by dimsav** [comment] 2017-04-04 15:47
The saved event is fired because when you save the model, translations are saved as well.

**Comment by Gummibeer** [comment] 2017-04-05 06:50
It is a question of faith.
I think the reason there is that the translations are meant as a part of the main model. But technical they aren't - they are an own model that's just related. And cause of this it's wrong to call these events on the main model.
More interesting is: why does it fire these events? It says: if nothing dirty and save of translations is successful fire these events. But if I just do `Model::first()->save()` there is nothing to save, not on main and not in translations. So `saveTranslations()` should return `false`.
And the other thing, I would recommend to add a `translating` and `translated` Event on the main model to overcome the problem with the wrong usage of existing events. The event can contain the main model and translation model, the locale is available on the translation model.

**Comment by reno1979** [comment] 2017-04-07 11:09
I think this is a reason why our current Trait/Observer is a bit  hard to get working. 

Our trait monitors the name field (which is also translated) and uses the saving event to rebuild another value on change of the name column. 

The dirty() array is empty though....  

I must agree with @Gummibeer here

**Comment by zsapkagy** [comment] 2017-04-10 14:38
Wouldn't be the **false** a better default value for the `saveTranslations()`?
Currently the `$model->save()` is always true on the main model like @Gummibeer said.
```php
    protected function saveTranslations()
    {
        $saved = true; // ???false???
        foreach ($this->translations as $translation) {
            if ($saved && $this->isTranslationDirty($translation)) {
                $translation->setAttribute($this->getRelationKey(), $this->getKey());
                $saved = $translation->save();
            }
        }
        return $saved;
    }
```

**Comment by Gummibeer** [comment] 2017-04-11 09:39
I think that this is a big issue with a lot of partial issues.

1. `saveTranslations()` returns true if nothing is done
2. the save events are fired on main model if nothing is saved there
3. translation events are missing

My way to solve all these things in a good way would be:
* `saveTranslations()` returns an array and not a single boolean - the locale as key and bool as value.
* don't fire save events on main model if itself isn't dirty
* add translation events on main model for each translation save

with these changes it doesn't fire save events falsly and and gives a better return for what it has saved or not. and it gives devs the option to do things before/after a translation.

I think that these changes are breaking and should be planned and have a propper versioning.

**Comment by dimsav** [comment] 2017-04-11 12:27
Thanks everyone for your input. Indeed the saveTranslations() method needs to be fixed. 

@Gummibeer what array should be the output of saveTranslations() in your opinion and why?

**Comment by reno1979** [comment] 2017-04-12 06:49
@dimsav @Gummibeer 

`saveTranslations()` should only return TRUE or FALSE. It saves or it doesn't. Finding out what went wrong is of course desirable, but it should not be by returning an array as default value.
Save events should indeed be left alone if there are no dirty values. 
Custom translated events are the way to go :)

**Comment by Gummibeer** [comment] 2017-04-12 09:28
@reno1979 And how will you handle it if there are 3 translations (de, en, fr). The de one is successful, the en one fails - what will happen with fr? and what will you return?
will it break after en and dont try to save fr and return false (current behaviour) or will it try fr but return false? And what should I do, as dev, with the false? Try as long as it returns true? or do I have to loop myself over all translations and have to check if this one was saved?

**Comment by reno1979** [comment] 2017-04-12 09:31
For now I use this function to detect a translation change 

``` 
/**
     * The translated model will be investeged to see if translateable fileds have 'dirty' values
     * @param  model $model
     * @param array $translatedFieldsToMonitor (defaults to the model translatedAttributes) Only values in this array will be looked for in the changes.
     * @return boolean
     */
    public static function hasChangedTranslatedFields(Model $model, array $translatedFieldsToMonitor = [])
    {
        $translatedAttributes = (empty($translatedFieldsToMonitor)) ? $model->translatedAttributes : $translatedFieldsToMonitor;
        $translatedAttributes = array_flip($translatedAttributes);
        $translations         = $model->translations;

        foreach ($translations as $translation) {
            $dirtyAttributes = $translation->getDirty();
            foreach ($dirtyAttributes as $dirtyAttributeName => $dirtyAttributeValue) {
                if (isset($translatedAttributes[$dirtyAttributeName])) {
                    return true;
                }
            }
        }

        return false;
    }

```

**Comment by reno1979** [comment] 2017-04-12 09:54
@Gummibeer If we have multiple translations, and a single one fails I would expect a FALSE. 

The save() did not succeed, even if it saved 2 out of 3.

What to do with a False? I think the cause should be fixed.

**Comment by Gummibeer** [comment] 2017-04-12 11:26
@reno1979 Ok, but the normal `save()` saves just a single model with a single query. Here we have n models with n queries. So we also have n return values. If you compress this to a single one you loose all needed debug informations and have to test it yourself which one failed.

But to make it short, how about a parameter `$compressed` to decide if you want a single bool or an array with all bools (array could be also an object with methods like the validator to check an overall fail or the state of a single locale).

*example of the object idea*
```php
$result = $model->saveTranslations();
$result->failed(); // overall fail
$result->localeFail('en'); // fail for locale
```

**Comment by reno1979** [comment] 2017-04-13 10:13
@Gummibeer 

What you are suggesting is some sort of debug mode, perhaps this could be new pull request.

I agree that it would help with debug tasks :)

**Comment by Gummibeer** [comment] 2018-05-15 13:11
I would suggest to remove these events cause they are fired on the single translation models if there is any change.

**Comment by dimsav** [comment] 2019-06-18 08:59
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).

**Closed by dimsav** 2019-06-18 08:59 UTC
Labels: bug, todo
